[package]
name = "cloudboot-lce"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
rusqlite = "0.31"
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
futures = "0.3.31"
r2d2_sqlite = "0.24"
r2d2 = "0.8.10"
